[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "apel_plugin"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = [
	     "python-auditor==0.0.6",
	     "pytz==2022.2.1",
	     "aiosqlite==0.17.0",
]

[project.optional-dependencies]
style = [
       "black",
       "flake8"
]
tests = [
      "pytest",
      "pytest-asyncio",
      "pytest-cov"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
source = ["src"]
omit = ["*__init__.py"]
branch = true

[tool.black]
line-length = 79
include = '\.pyi?$'