name: pypi-publish

on:
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install build
        run: |
          pip install --upgrade pip
          pip install build --user
      - name: Build binary wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy
      
